# Generated by Django 3.2.2 on 2021-05-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default=False, help_text='Dueño del hilo', max_length=150)),
                ('text', models.TextField(blank=True, default='', help_text='Texto del hilo')),
                ('isMediaFiles', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default=False, help_text='Dueño del hilo', max_length=150)),
                ('text', models.TextField(blank=True, default='', help_text='Texto del hilo')),
                ('isMediaFiles', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('toThread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.thread')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
