# Generated by Django 3.2.2 on 2021-05-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20210509_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='owner',
            field=models.CharField(help_text='Dueño del hilo', max_length=150),
        ),
    ]
