# Generated by Django 3.2.2 on 2021-05-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_alter_thread_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='ownerCity',
            field=models.CharField(default='', help_text='Ciudad en donde se creo el hilo', max_length=100),
        ),
        migrations.AddField(
            model_name='thread',
            name='ownerCountry',
            field=models.CharField(default='CO', max_length=10),
        ),
    ]
