# Generated by Django 3.2.3 on 2021-10-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_channel_tag'),
        ('threads', '0006_thread_nativelenguaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channels.channel'),
        ),
    ]
