# Generated by Django 3.2.2 on 2021-05-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='name',
            field=models.CharField(default=1, help_text='Nombre de la reaccion', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reaction',
            name='image',
            field=models.ImageField(help_text='Imagen de la reaccion', upload_to='reactions'),
        ),
    ]
