# Generated by Django 3.2.3 on 2021-05-15 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_alter_thread_id'),
        ('reactions', '0003_threadreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadreaction',
            name='ownerReaction',
            field=models.CharField(help_text='Creador de la reaccion', max_length=100),
        ),
        migrations.AlterField(
            model_name='threadreaction',
            name='reaction',
            field=models.ForeignKey(help_text='Reaccion', on_delete=django.db.models.deletion.CASCADE, to='reactions.reaction'),
        ),
        migrations.AlterField(
            model_name='threadreaction',
            name='thread',
            field=models.ForeignKey(help_text='Hilo', on_delete=django.db.models.deletion.CASCADE, to='threads.thread'),
        ),
    ]
