# Generated by Django 3.2.3 on 2021-10-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank='', max_length=270, null=True)),
                ('rules', models.CharField(max_length=300)),
                ('visibilityMode', models.BooleanField(default=True)),
                ('dateCreate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
