# Generated by Django 3.2.3 on 2021-10-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='tag',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
